[pytest]
# Ignore the existing testing_library scripts as they are not unit tests
norecursedirs = src/testing_library playwright_tests .git venv

# Optional: Add src to python path so you can import your modules easily in tests
pythonpath = . src

# Optional: async support
asyncio_mode = auto
